tap "cdalvaro/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "asdf"
brew "bat"
brew "cdalvaro/tap/wxmac"
brew "diff-so-fancy"
brew "fd"
brew "fzy"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "pinentry-mac"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "unzip"
brew "watch"

cask "1password"
cask "alacritty"
cask "appcleaner"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "monitorcontrol"
cask "spotify"
cask "sublime-text"
cask "tableplus"

mas "Magnet", id: 441258766

