"
" Preamble
"
set encoding=utf-8
set nocompatible

" Paths
let vim_dir=$HOME.'/.config/vim'
let &backupdir=vim_dir.'/backup//'
let &directory=vim_dir.'/swap//'
let &runtimepath.=','.vim_dir.','.vim_dir.'/after'
let &viminfo.=',n'.vim_dir.'/.viminfo'
let g:netrw_home=vim_dir

"
" Plug
"

" Setup
if empty(glob(vim_dir.'/autoload/plug.vim'))
  silent execute '!curl -fLo '.vim_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin(vim_dir . '/plugs')

Plug 'elixir-editors/vim-elixir', {'for': 'elixir'}
Plug 'mhinz/vim-mix-format', {'for': 'elixir'}
Plug 'mileszs/ack.vim'
Plug 'prabirshrestha/async.vim'
Plug 'srstevenson/vim-picker'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

" ack.vim
let g:ackprg = 'ag --vimgrep'
nnoremap <C-f> :Ack!<Space>

" vim-picker
nnoremap <C-p> :PickerEdit<CR>
nnoremap <C-p>h :PickerSplit<CR>
nnoremap <C-p>t :PickerTabedit<CR>
nnoremap <C-p>v :PickerVsplit<CR>

"
" Editing
"
colorscheme mime
filetype plugin indent on
set clipboard=unnamed
set ruler
set showmatch
set showmode
set undodir=~/.config/vim/undo//
syntax on

" Autosave
augroup autosave_buffer
	au FocusLost,WinLeave * :silent! wa
	au FocusGained,BufEnter * :silent! !
augroup END

" Lines
augroup autoswitch_number_relativenumber
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
set number relativenumber
set scrolloff=50

" Mouse
set mouse=
set mousehide

" Search
set incsearch
set hlsearch
nnoremap <CR> :noh<CR>

" Spacing
set autoindent
set backspace=indent,eol,start
set copyindent
set expandtab
set shiftwidth=2
set smarttab
set tabstop=2

"
" Windowing
"
set splitbelow
set splitright

"
" netrw
"
let g:netrw_liststyle = 3
let g:netrw_banner = 0

" tmux
autocmd VimResized * :wincmd =

