#!/bin/sh

function install_dotfiles_cmd {
  local dotfiles_repository="git@github.com:cgerling/dotfiles.git"
  local dotfiles_path="$HOME/.dotfiles.git"

  function dot {
     /usr/bin/git --git-dir="$dotfiles_path" --work-tree=$HOME $@
  }

  function install_dotfiles_run {
    if [ -d "$dotfiles_path" ]; then
      echo "$dotfiles_path already exists, skipping clone step.";
    else
      git clone --bare "$dotfiles_repository" "$dotfiles_path"
    fi

    mkdir -p .config-backup

    dot checkout

    if [ $? = 0 ]; then
      echo "Checked out config.";
    else
      echo "Deleting conflicting files";
      dot checkout 2>&1 | egrep "\s+\." | awk {'print &1'} | xargs -I{} rm -f {}
    fi;

    dot checkout

    echo "Initializing submodules...";
    dot submodule update --init --recursive

    dot config status.showUntrackedFiles no
  }

  install_dotfiles_run $@
}

install_dotfiles_cmd $@
